version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=roombooking
      - MYSQL_ROOT_PASSWORD=12345678@Abc
      - MYSQL_USER=pttam
      - MYSQL_PASSWORD=12345678@Abc
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - '13306:3306'
    volumes:
      - ./dbs:/var/lib/mysql
    networks:
      - my_network_custom
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '1234:80'
    environment:
      - PMA_HOST=db
      - PMA_USER=pttam
      - PMA_PASSWORD=12345678@Abc
      - PMA_ARBITRARY=1
    networks:
      - my_network_custom
    depends_on:
      - db
networks:
  my_network_custom:
    driver: bridge
